name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: rails_7_0
            ruby: 2.7
          - gemfile: rails_7_0
            ruby: 3.0
          - gemfile: rails_7_0
            ruby: 3.1

          - gemfile: rails_7_1
            ruby: 2.7
          - gemfile: rails_7_1
            ruby: 3.0
          - gemfile: rails_7_1
            ruby: 3.1
          - gemfile: rails_7_1
            ruby: 3.2

          - gemfile: rails_7_2
            ruby: 3.1
          - gemfile: rails_7_2
            ruby: 3.2
          - gemfile: rails_7_2
            ruby: 3.3

    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run specs
      run: bundle exec rspec
